### ISSUE TITLE
`uk` instead of expected `gb` is returned

### ISSUE THREAD

**Issue by KES777** [SBECK-github/Locale-Codes#13]
```perl
 $obj->name2code( 'United Kingdom of Great Britain and Northern Ireland' ) # gb expected
```

actual result: `uk`

This cause problems for `Number::Phone` which expects `gb` for country and does not create legit phone numbers when `uk` is passed:

```perl
Number::Phone->new( 'uk', '7624 463278'); # undef
# expected: Number::Phone::UK::IM \+447624463278
# if Locale::Codes returns correct `gb` country code
```
See [commit](https://github.com/DrHyde/perl-modules-Number-Phone/commit/c34782ddc8cb00601bd02fdec8b0d65fc235fd2d#diff-6177712750032e69dd78f52ef9217067c1148c9c5a2605427b426c3e27be68eaR737)

**Comment by SBECK-github** [comment]
Could you please tell me what version of Locale::Codes you are using?  I just ran your example and got the expected 'gb'.  If you send me the output of $obj->version(), that will help.

**Comment by KES777** [comment]
Yes, not reproducible when I tried on clean project. After that found that our code do renames: `Locale::Country::rename_country_code('gb', 'uk');`

Thank you, sorry for missreport.
