### ISSUE TITLE
Point correct issue tracker from metacpan

### ISSUE THREAD

**Issue by KES777** [SBECK-github/Locale-Codes#14]
![image](https://user-images.githubusercontent.com/799021/167595287-d488194b-3a85-42ba-9717-f2049dfd32c0.png)

point to https://rt.cpan.org/Public/Dist/Display.html?Name=Locale-Codes

Can you please change that link to github?
example: https://metacpan.org/release/BIGPRESH/Dancer-1.3513/source/META.json#L399

Thank you.

**Comment by SBECK-github** [comment]
Thanks for the suggestion.  I wasn't aware that I could change that.  The next release will point to the github issue tracker.
