### ISSUE TITLE
Locale-Codes-3.75: Warning: the following files are missing in your kit

### ISSUE THREAD

**Issue by twata1** [SBECK-github/Locale-Codes#18]
Hello,

Running Strawberry Perl 5.38.0, I noticed the following message.

```
C:\home\skyfish>cpan SBECK/Locale-Codes-3.75.tar.gz

(snip)

Checking if your kit is complete...
Warning: the following files are missing in your kit:
        pm_to_blib
Please inform the author.
Generating a gmake-style Makefile
Writing Makefile for Locale::Codes
Writing MYMETA.yml and MYMETA.json
(C:\strawberry-perl-5.38.0.1-64bit-portable\perl\bin\perl.exe Makefile.PL exited with 0)

(snip)

```

Thank you,

**Comment by oalders** [comment]
To add to this, `Locale::Codes` is not being shown by MetaCPAN for what appears to be a related reason. It's listing documentation and examples, but no code: https://metacpan.org/release/SBECK/Locale-Codes-3.75

`META.json` is now pointing at `blib/lib` for the modules whereas the previous release used `lib`. The release however does not include a `blib` dir. See https://metacpan.org/release/SBECK/Locale-Codes-3.75/diff/SBECK%2FLocale-Codes-3.74#META.json

**Comment by SBECK-github** [comment]
Somehow I messed up the 3.75 release.  I'm releasing a new version today with this fixed.

**Comment by SBECK-github** [comment]
Should be fixed now.
