### ISSUE TITLE
Missing alpha-3 code

### ISSUE THREAD

**Issue by pierresigwalt** [SBECK-github/Locale-Codes#2]
Hi,

We were using the library and saw that some of the alpha-3 code are missing compare to an official website: http://www.iso.org/iso/country_codes

**Missing list:**

No ISO-3 for
- Antarctica
- Bouvet Island
- British Indian Ocean Territory
- Christmas Island
- Cocos (Keeling) Islands
- French Southern Territories
- Heard Island and McDonald Islands
- South Georgia and the South Sandwich Islands
- Taiwan, Province of China[a]
- United States Minor Outlying Islands

Is there is any reason for this? If no would it be possible to add it?

Thank you very much for your response

Best Regards

**Comment by SBECK-github** [comment]
What version are you using?  I checked the first 5 of these and all of them are present.

<pre>
use Locale::Codes::Country;
country2code('Antarctica','alpha-3');
   => ata
country2code('Bouvet Island','alpha-3');
   => bvt
</pre>

Please verify that you are using the most recent version (I do not know off hand when these were added, and they may not be present in an older version).  Also, include a sample script that shows the failure.

Thanks

**Comment by pierresigwalt** [comment]
Perfect, thank you for your answer I was using 3.21. by upgrading the version all is good now.

Best Regards
