### ISSUE TITLE
version 3.41 no longer parses Czech Republic

### ISSUE THREAD

**Issue by mintsoft** [SBECK-github/Locale-Codes#3]
Hello,

Previously this worked: `perl -e 'use Locale::Country; print country2code("Czechia");'` now it outputs empty string. I think this is due to https://github.com/SBECK-github/Locale-Codes/commit/1cbc9a5ba63c1df6f4dca96400372762411c9afc#diff-6ead1c515ffc87b95c67ec8d20fc350d as it now only works with `Czechia` (the UN short name - http://unterm.un.org/UNTERM/Display/Record/UNHQ/NA/4275087d-4018-4082-899d-95f37efeda65).

I don't think this is correct? I belive the full name should be accepted in `country2code` ?

**Comment by SBECK-github** [comment]
I will release a version tomorrow which corrects this.

**Comment by mintsoft** [comment]
Thanks @SBECK-github
