### ISSUE TITLE
Legacy functional interface generates warnings at/after v3.50

### ISSUE THREAD

**Issue by dmaestro** [SBECK-github/Locale-Codes#4]
Because the default of err is true in Locale::Codes::new, Locale::Country generates warnings when using the legacy interface with invalid values, where it did not previously:
```
$ perl -MLocale::Country -E 'say defined code2country("Invalid") ? "" : "Not ", "Defined."'
ERROR: _code: code not in codeset: invalid [alpha-2]
 at /opt/perl5/perlbrew/perls/perl-5.16.3/lib/5.16.3/Locale/Country.pm line 41.
Not Defined.
$
```

This breaks legacy code which is sensitive to warnings.

Please change the default to err => 0 when creating the object used by the legacy (functional) interface.

**Comment by SBECK-github** [comment]
I will change this immediately.  Sorry I missed that.  I will get a new release out shortly.

**Comment by SBECK-github** [comment]
A new release is available which corrects this.
Thanks for pointing out this problem.
